# Generated by Django 5.2.1 on 2025-05-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_workspace_tag_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
